sudo: required
dist: bionic

notifications:
  email: false
  slack: polyengine:Fah16tvbyOphIl7FGHAVVhaB

# Enable C++ support
language: cpp

# Enable compiler cache to speed up compilation
cache: ccache

matrix:
  include:
    - os: linux
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
    - os: linux
      env:
        - MATRIX_EVAL="CC=clang-9 && CXX=clang++-9"
    - os: osx
      osx_image: xcode11.4

 
before_install:
  - eval "${MATRIX_EVAL}"
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      # Add Qt 5.10.1 ppa
      sudo add-apt-repository -y ppa:jonathonf/gcc-9.2
      sudo apt update -qq
      sudo apt install -y git make cmake python3 python3-pip clang-9 g++-9 gcc-9
      sudo apt install -y mesa-common-dev libgl1-mesa-dev qt5-default
    elif [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      brew unlink python@2
      brew update && brew bundle --file=.Brewfile
    fi
  - sudo pip3 install --upgrade pip
  - sudo pip3 install gitpython appdirs docker

#install:

before_script:
  ############################################################################
  # Go back to the root of the project and setup the build directory
  ############################################################################
  - cd ${TRAVIS_BUILD_DIR}
  - cd PolyEngine/Scripts
  - python3 ./pe_tools.py initialize_submodules
  - python3 ./pe_tools.py update_engine_project
  - python3 ./pe_tools.py create_game_project ${TRAVIS_BUILD_DIR}/TestGame TestGame
  
script:
  - cd ${TRAVIS_BUILD_DIR}/PolyEngine/Build
  - cmake -D CMAKE_C_COMPILER=$CC -D CMAKE_CXX_COMPILER=$CXX ..
  - make
  - cd ${TRAVIS_BUILD_DIR}/TestGame/Build
  - cmake -D CMAKE_C_COMPILER=$CC -D CMAKE_CXX_COMPILER=$CXX ..
  - make
  - ls ${TRAVIS_BUILD_DIR}
  - ${TRAVIS_BUILD_DIR}/PolyEngine/Dist/Debug/PolyCoreTests
  - ${TRAVIS_BUILD_DIR}/PolyEngine/Dist/Debug/PolyAPITests
  - ${TRAVIS_BUILD_DIR}/PolyEngine/Dist/Debug/PolyEngineTests
  - python3 ${TRAVIS_BUILD_DIR}/PolyEngine/Scripts/pe_tools.py run_tests

