notifications:
  email: false
  slack: polyengine:Fah16tvbyOphIl7FGHAVVhaB

# Enable C++ support
language: cpp
# Compiler selection
compiler:
  - clang
  - gcc
# Build steps
script:
  - cd PolyEngine
  - mkdir build
  - cd build
  - cmake .. && make
